// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBryUOt9ITqrNB-JrRHyHKRCQNaMINg_iA',
    appId: '1:914001134860:web:80e688ad9e57dff57e3529',
    messagingSenderId: '914001134860',
    projectId: 'ynov-hackathon25-gr3',
    authDomain: 'ynov-hackathon25-gr3.firebaseapp.com',
    storageBucket: 'ynov-hackathon25-gr3.firebasestorage.app',
    measurementId: 'G-3EV8MQQXCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3lPQgazluVZQ01aVvP35PWSSI_frvYHs',
    appId: '1:914001134860:android:da0802a3ec18290d7e3529',
    messagingSenderId: '914001134860',
    projectId: 'ynov-hackathon25-gr3',
    storageBucket: 'ynov-hackathon25-gr3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjX_mLP-F0fx24tUQNnLGKZ03o-jMBXsM',
    appId: '1:914001134860:ios:27d5424817230c3a7e3529',
    messagingSenderId: '914001134860',
    projectId: 'ynov-hackathon25-gr3',
    storageBucket: 'ynov-hackathon25-gr3.firebasestorage.app',
    iosBundleId: 'com.example.hackaton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjX_mLP-F0fx24tUQNnLGKZ03o-jMBXsM',
    appId: '1:914001134860:ios:27d5424817230c3a7e3529',
    messagingSenderId: '914001134860',
    projectId: 'ynov-hackathon25-gr3',
    storageBucket: 'ynov-hackathon25-gr3.firebasestorage.app',
    iosBundleId: 'com.example.hackaton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBryUOt9ITqrNB-JrRHyHKRCQNaMINg_iA',
    appId: '1:914001134860:web:ec73e8ac5e80f04f7e3529',
    messagingSenderId: '914001134860',
    projectId: 'ynov-hackathon25-gr3',
    authDomain: 'ynov-hackathon25-gr3.firebaseapp.com',
    storageBucket: 'ynov-hackathon25-gr3.firebasestorage.app',
    measurementId: 'G-DLXRLH41JX',
  );
}
